"""Add transport_options to rider_profiles

Revision ID: 0628c1c9f3e7
Revises: 303211f93eb4
Create Date: 2025-09-08 08:35:02.916482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0628c1c9f3e7'
down_revision: Union[str, Sequence[str], None] = '303211f93eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rider_profiles', sa.Column('transport_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider_profiles', 'transport_options')
    # ### end Alembic commands ###
