"""add rider address fields

Revision ID: ab7c4361afc8
Revises: 62031394684f
Create Date: 2025-09-12 11:41:49.906208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7c4361afc8'
down_revision: Union[str, Sequence[str], None] = '62031394684f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rider_profiles', sa.Column('house_number_addition', sa.String(length=20), nullable=True))
    op.add_column('rider_profiles', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('rider_profiles', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('rider_profiles', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('rider_profiles', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('rider_profiles', sa.Column('geocode_confidence', sa.Float(), nullable=True))
    op.add_column('rider_profiles', sa.Column('needs_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rider_profiles', 'needs_review')
    op.drop_column('rider_profiles', 'geocode_confidence')
    op.drop_column('rider_profiles', 'lon')
    op.drop_column('rider_profiles', 'lat')
    op.drop_column('rider_profiles', 'country_code')
    op.drop_column('rider_profiles', 'street')
    op.drop_column('rider_profiles', 'house_number_addition')
    # ### end Alembic commands ###
